name: anne_bebek
description: A new Flutter project.


publish_to: 'none'

version: 1.0.8+8

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: any
  email_validator: ^2.0.1
  fluttertoast: ^8.0.9
  firebase_database: ^9.0.16
  onboarding: ^3.1.0
  shared_preferences: ^2.0.15
  video_player: ^2.4.5
  http: ^0.13.3
  timeago: ^3.3.0
  flutter_local_notifications: ^9.8.0+1


  cupertino_icons: ^1.0.2
  firebase_auth: ^3.4.2
  firebase_messaging: ^12.0.3
  cloud_functions: ^3.3.5
  package_info: ^2.0.2
  url_launcher: ^6.1.5
  sticky_headers: ^0.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/

